### 2. Creating numpy array(1D,2D,3D......)

In [3]:
import numpy as np

In [4]:
# 1D numpy array

arr1 = np.array([1,2,3,4,5])
print(arr1)

# checking type of array
print(type(arr1))

# datatype of numpy array elements
print(type(arr1.dtype))

[1 2 3 4 5]
<class 'numpy.ndarray'>
<class 'numpy.dtype[int32]'>


In [5]:
# checking dimentions of an array

arr1.ndim

1

In [7]:
# float elements into numpy array
# if we insert one float value into array than the entire array converts into float values.

arr1 = np.array([1,2,3,4,5.5])
print(arr1)
print(type(arr1))
print(arr1.dtype)

[1.  2.  3.  4.  5.5]
<class 'numpy.ndarray'>
float64


In [8]:
arr1 = np.array([1,2,3,'hello',5.5])
print(arr1)
print(type(arr1))
print(arr1.dtype)

# U32 : unicode string type with 32 length

['1' '2' '3' 'hello' '5.5']
<class 'numpy.ndarray'>
<U32


In [9]:
# 2D numpy array

arr2 = np.array([['Bahubali','Devara','Kanthara'],['Prabhas','NTR','Rishab Shetty']])
print(arr2)
print(arr2.ndim)

[['Bahubali' 'Devara' 'Kanthara']
 ['Prabhas' 'NTR' 'Rishab Shetty']]
2


In [10]:
# To check the shape of an array 
arr2.shape

(2, 3)

In [11]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
# 3D numpy array : we can create 3D array by using 2d arrays.
arr3 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
arr3
                 

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [15]:
arr3.ndim

3

In [16]:
arr3.shape

(2, 2, 3)

In [18]:
# 4D NUMPY ARRAY
arr4 = np.array([[[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]],[[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]]])
arr4
                

array([[[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]],


       [[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]]])

In [19]:
arr4.ndim

4

In [20]:
arr4.shape

(2, 2, 2, 3)