### Size and data type convertion

In [2]:
import numpy as np

In [3]:
# size: number of elements in the numpy array
songs = np.array(['Monica','Fear song','Peelings'])
songs.size

3

In [4]:
songs.dtype

dtype('<U9')

In [5]:
song_duration = np.array([3.58,3.2,5.09])
int_arr = song_duration.astype(int) # converting float data type into integer.
int_arr

array([3, 3, 5])

In [6]:
# string to int converstion
song_earning = np.array(['500','300','1000'])

song_earning.dtype

dtype('<U4')

In [7]:
int_arr = song_earning.astype(int) # converting string into integer
int_arr

array([ 500,  300, 1000])

In [8]:
float_arr = song_earning.astype(float)
float_arr

array([ 500.,  300., 1000.])

In [9]:
np.array([True,False,True]).astype(int) # converting boolean values into integers.

array([1, 0, 1])

In [10]:
np.array([0,-1,4,5]).astype(bool) # converting integers into boolean.

array([False,  True,  True,  True])