### Mathematical and statistical operations

In [2]:
import numpy as np

In [3]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr + 10) # adding 10 to every element in an array.

[[11 12 13]
 [14 15 16]]


In [4]:
# multiplying 2 to every element in an array.
print(arr * 2)

[[ 2  4  6]
 [ 8 10 12]]


In [5]:
print(arr ** 2)

[[ 1  4  9]
 [16 25 36]]


In [6]:
print(arr - 1)

[[0 1 2]
 [3 4 5]]


In [8]:
salary = np.array([10,15,25,30,35,50,80,45,60,75,100,155])

# sum of all the salaries
np.sum(salary)

np.int64(680)

In [9]:
# finding minimum salary
np.min(salary)

np.int64(10)

In [10]:
# max of salary
np.max(salary)

np.int64(155)

In [11]:
# average of salary
np.mean(salary)

np.float64(56.666666666666664)

In [12]:
# variance of a salary
np.var(salary)

np.float64(1559.7222222222226)

In [13]:
# standard deviation
np.std(salary)

np.float64(39.49331870357596)

In [14]:
# finding percentile of a salary at 75 percentage
np.percentile(salary,75)

np.float64(76.25)

In [15]:
# finding percentile of salary in decimal percentage value
np.percentile(salary,0.75)

np.float64(10.4125)

In [17]:
# argmin() : finding the minimum value index
np.argmin(salary)

np.int64(0)

In [18]:
# argmax() : finding max value index position
np.argmax(salary)

np.int64(11)

In [19]:
# finding log value with base 10
np.log10(1000)

np.float64(6.907755278982137)

In [20]:
# finding log value with base 2
np.log2(20)

np.float64(4.321928094887363)

In [21]:
# finding log value with constant base e = 2.71
np.log(50)

np.float64(3.912023005428146)

In [22]:
# finding square root of a value
np.sqrt(300)

np.float64(17.320508075688775)

In [23]:
# rounding the float value upto n positions
pi = 3.1752
np.round(pi)

np.float64(3.0)

In [24]:
np.floor(pi)

np.float64(3.0)

In [25]:
np.ceil(pi)

np.float64(4.0)

In [26]:
# finding absolute value which means giving positive value for any value
np.abs(-23)

np.int64(23)

In [29]:
fruits = np.array(['apple','banana','grapes','orange','mango'])
np.sort(fruits) # sorting in a lexographical order.

array(['apple', 'banana', 'grapes', 'mango', 'orange'], dtype='<U6')

In [32]:
fruits_price = np.array([150,50,80,100,200])
np.sort(fruits_price)

array([ 50,  80, 100, 150, 200])

In [33]:
# sorting the prices and reversing it.
np.sort(fruits_price)[::-1]

array([200, 150, 100,  80,  50])

In [34]:
arr = np.array([[10,5,15],[20,35,15]])
np.sort(arr)

array([[ 5, 10, 15],
       [15, 20, 35]])