### Concatination, stack, split on numpy array

In [1]:
import numpy as np

In [4]:
# concatination() : used to merge the two or more numpy arrays as one array
# 1D array concatenation
arr1 = np.array([10,100,500])
arr2 = np.array([0,-500,20])

arr = np.concatenate((arr1,arr2))
print(arr)

[  10  100  500    0 -500   20]


In [5]:
# 2D array concatenation
arr1 = np.array([[3,1,5],[6,2,3]])
arr2 = np.array([[100,200,5000],[600,100,300]])
arr = np.concatenate((arr1,arr2),axis = 1) # if axis = 1 it will be column wise concatination
print(arr)

[[   3    1    5  100  200 5000]
 [   6    2    3  600  100  300]]


In [11]:
# 2D array concatenation
arr1 = np.array([[3,1,5],[6,2,3]])
arr2 = np.array([[100,200,5000],[600,100,300]])
arr = np.concatenate((arr1,arr2),axis = 0) # if axis = 0 it will be row wise wise concatination
print(arr)

[[   3    1    5]
 [   6    2    3]
 [ 100  200 5000]
 [ 600  100  300]]


In [13]:
# interview question
# concatenate() function cannot concatenate the different dimention array

a = np.array([1,2,3])
b = np.array([[4,5,6]])
np.concatenate((a,b),axis = 1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [14]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9]])
np.concatenate((a,b),axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
# columns and rows should be same when we are doing concatination
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9]])
np.concatenate((a,b),axis = 1) #  

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [16]:
# stack() : It is also used for merging numpy arrays.
# stack() function will add one extra dimention in the output array.

arr1 = np.array([10,100,500])
arr2 = np.array([0,-500,20])
stacked_arr = np.stack((arr1,arr2),axis = 0)
print(stacked_arr)

[[  10  100  500]
 [   0 -500   20]]


In [19]:
np.concatenate((arr1,arr2),axis = 0)

array([  10,  100,  500,    0, -500,   20])

In [18]:
stacked_arr = np.stack((arr1,arr2),axis = 1)
print(stacked_arr)

[[  10    0]
 [ 100 -500]
 [ 500   20]]


In [21]:
# 2D array stack operation
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[11,12,13]])
stack_2d = np.stack((arr1,arr2),axis = 0) # row wise stacking
stack_2d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [11, 12, 13]]])

In [22]:
stack_2d = np.stack((arr1,arr2),axis = 1) # column wise wise stacking
stack_2d

array([[[ 1,  2,  3],
        [ 7,  8,  9]],

       [[ 4,  5,  6],
        [11, 12, 13]]])

In [25]:
# interview question : stacking of two different dimentional arrays are not possible.
a = np.array([1,2,3])
b = np.array([[4,5,6]])
np.stack((a,b),axis = 1)

ValueError: all input arrays must have the same shape

In [27]:
# vstack() : vertical stacking
# It is similar to vertical concatenation or vertical stack
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[11,12,13]])

np.vstack((arr1,arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [28]:
# hstack() - horizontal concatenation
# It is similar to horizontal concatenation
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[11,12,13]])

np.hstack((arr1,arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 11, 12, 13]])

In [7]:
# stack() - axis = 0,1,2,3,4,5.......

arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[10,11,12],[13,14,15],[16,17,18]])

arr = np.stack((arr1,arr2),axis = 0)
arr

# axis : tell us at which location new dimention will be added.
# n = 2 : number of input arrays
# axis = k : a1,a2,a3,a4.....akN
# axis = 2 : 3,3,2
#axis = 1 : 3,2,3
# axis = 0 : 2,3,3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

# split() - This will split the numpy array

In [13]:
arr1 = np.array([10,20,30,40,28,50,70,35,80])
split_arr = np.split(arr1,3)
print(split_arr)
type(split_arr)

[array([10, 20, 30]), array([40, 28, 50]), array([70, 35, 80])]


list

In [15]:
print(split_arr[0])
print(split_arr[1])
print(split_arr[2])

[10 20 30]
[40 28 50]
[70 35 80]


In [17]:
print(split_arr[0][0])

10


In [19]:
# split on 2D array
arr1 = np.array([[20,30,40],[10,15,30],[70,90,55]])
split_arr = np.split(arr1,3) # converting every array into 2D array
split_arr

[array([[20, 30, 40]]), array([[10, 15, 30]]), array([[70, 90, 55]])]

In [20]:
split_arr[0]

array([[20, 30, 40]])