In [6]:
## NumPy Queries for Indian Cricket Team Dataset

In [7]:

Query 4: Count the total number of players above 30 years old.
Query 5: Find the median batting average.
Query 6: Find the standard deviation of strike rates.
Query 7: Find the 90th percentile of batting average.
Query 8: Find the number of players with strike rate above 150.
Query 9: Reshape the first 20 batting averages into a 4x5 matrix.
Query 10: Compute row-wise sum of reshaped matrix.
Query 11: Compute column-wise mean of reshaped matrix.
Query 12: Transpose the reshaped matrix.
Query 13: Find the variance of batting average.
Query 14: Stack age and matches played horizontally.
Query 15: Split the batting average array into 5 equal parts.


SyntaxError: invalid decimal literal (953391547.py, line 4)

In [8]:
import numpy as np
import pandas as pd
df = pd.read_csv("Indian_Cricket_Team_Dataset.csv")
Age = df['Age']

In [9]:
# Query 1: Convert 'Age' column to a NumPy array.

arr_age = np.array(Age)
arr_age

array([26, 23, 32, 34, 30, 27, 32, 24, 26, 29, 22, 26, 30, 30, 27, 24, 23,
       27, 27, 22, 25, 24, 21, 27, 31, 33, 25, 21, 35, 31, 24, 20, 31, 29,
       25, 32, 31, 28, 20, 30, 30, 34, 29, 35, 31, 31, 35, 34, 33, 33, 34,
       33, 22, 31, 26, 23, 35, 28, 22, 24, 22, 26, 24, 28, 26, 21, 23, 28,
       31, 33, 21, 29, 28, 29, 24, 21, 23, 31, 34, 31, 26, 31, 32, 27, 34,
       22, 33, 20, 23, 21, 27, 23, 21, 33, 25, 25, 29, 23, 25, 32, 34, 21,
       29, 31, 21, 29, 33, 23, 33, 34, 35, 34, 27, 33, 26, 31, 28, 33, 27,
       24, 35, 32, 21, 34, 24, 27, 29, 28, 31, 31, 31, 32, 28, 32, 34, 32,
       20, 28, 26, 28, 27, 20, 31, 27, 27, 34, 30, 22, 20, 27, 22, 22, 20,
       30, 24, 29, 26, 29, 28, 31, 26, 28, 27, 31, 21, 20, 35, 26, 26, 33,
       27, 24, 22, 31, 27, 25, 30, 22, 20, 22, 24, 34, 33, 22, 20, 24, 29,
       26, 34, 33, 26, 30, 28, 34, 34, 29, 29, 31, 32, 22, 34, 35, 26, 20,
       23, 32, 35, 23, 33, 24, 26, 26, 32, 34, 30, 32, 23, 32, 35, 26, 30,
       22, 25, 31, 21, 29

In [10]:
# Query 2: Find the average age of players.
np.mean(arr_age)

np.float64(27.57)

In [11]:
# Query 3: Find the oldest and youngest player age.
# oldest player age
print(np.max(arr_age))
# youngest player age
print(np.min(arr_age))


35
20


In [12]:
# Query 4: Count the total number of players above 30 years old.
count = np.sum(arr_age > 30)
count

np.int64(336)

In [13]:
#Query 5: Find the median batting average.
batting_avg = df['Batting Average']
print(np.median(batting_avg))

40.135


In [14]:
#Query 6: Find the standard deviation of strike rates.
Strike_Rate = df['Strike Rate']
print(np.std(Strike_Rate))

29.108194103844706


In [15]:
# Query 7: Find the 90th percentile of batting average.
np.percentile(batting_avg,90)

np.float64(55.323)

In [16]:
# Query 8: Find the number of players with strike rate above 150.
count = np.sum(Strike_Rate > 150)
count

np.int64(513)

In [25]:
# Query 9: Reshape the first 20 batting averages into a 4x5 matrix.
arr = df['Batting Average'].head(20)
arr1 = np.array(arr)
a = arr1.reshape(4,5)
a

array([[27.7 , 24.61, 36.87, 51.81, 49.8 ],
       [22.2 , 38.21, 40.9 , 45.78, 46.01],
       [34.59, 42.43, 39.24, 55.4 , 41.21],
       [37.64, 36.18, 42.9 , 52.16, 41.54]])

In [24]:
# Query 10: Compute row-wise sum of reshaped matrix.
np.sum(a,axis = 0)

array([122.13, 141.43, 159.91, 205.15, 178.56])

In [26]:
# Query 11: Compute column-wise mean of reshaped matrix.
np.mean(a,axis = 1)

array([38.158, 38.62 , 42.574, 42.084])

In [28]:
# Query 12: Transpose the reshaped matrix.
arr = a.T
arr

array([[27.7 , 22.2 , 34.59, 37.64],
       [24.61, 38.21, 42.43, 36.18],
       [36.87, 40.9 , 39.24, 42.9 ],
       [51.81, 45.78, 55.4 , 52.16],
       [49.8 , 46.01, 41.21, 41.54]])

In [29]:
# Query 13: Find the variance of batting average.
np.var(batting_avg)

131.5398293159

In [32]:
# Query 14: Stack age and matches played horizontally.
matches = df['Matches Played']
np.hstack((Age,matches))

array([ 26,  23,  32, ..., 126,  16, 146])

In [36]:
# Query 15: Split the batting average array into 5 equal parts.
arr = np.array(batting_avg)
np.split(arr,5)

[array([27.7 , 24.61, 36.87, 51.81, 49.8 , 22.2 , 38.21, 40.9 , 45.78,
        46.01, 34.59, 42.43, 39.24, 55.4 , 41.21, 37.64, 36.18, 42.9 ,
        52.16, 41.54, 46.47, 49.51, 40.81, 37.07, 55.07, 36.7 , 38.48,
        59.61, 20.01, 27.42, 35.36, 57.3 , 22.8 , 20.38, 22.11, 23.54,
        21.5 , 39.19, 43.23, 30.87, 35.93, 23.67, 33.45, 40.9 , 49.29,
        20.13, 38.69, 31.88, 54.11, 48.62, 43.56, 31.09, 56.41, 21.8 ,
        24.38, 35.67, 24.98, 58.26, 51.92, 30.36, 43.54, 59.29, 55.37,
        44.03, 56.15, 59.57, 49.73, 22.6 , 36.06, 53.51, 29.22, 53.23,
        24.81, 21.88, 35.36, 21.47, 58.29, 53.05, 52.03, 45.19, 28.65,
        40.73, 43.89, 41.  , 30.41, 40.61, 39.65, 59.85, 55.9 , 38.54,
        44.92, 49.91, 21.39, 55.8 , 54.41, 38.3 , 35.65, 30.92, 39.07,
        21.78, 54.09, 21.42, 33.16, 57.26, 49.41, 31.26, 30.11, 20.2 ,
        47.83, 21.95, 41.3 , 58.48, 24.38, 55.78, 59.66, 22.46, 55.32,
        40.64, 56.26, 42.85, 46.48, 41.75, 54.58, 49.36, 40.85, 54.73,
      