### 3. Special type of numpy array

In [1]:
import numpy as np

In [2]:
# Numpy array which initialize with Zero

# 1D zero array
zero_arr = np.zeros(5)
zero_arr

array([0., 0., 0., 0., 0.])

In [3]:
# 2D zero array
zero_arr = np.zeros((2,3))
zero_arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
# 3D zero array
zero_arr = np.zeros(((2,2,3)))
zero_arr

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [5]:
# creating numpy array which are initialize with ones.

# 1D one's array

ones_arr = np.ones(5)
ones_arr

array([1., 1., 1., 1., 1.])

In [6]:
# 2D one's array

ones_arr = np.ones((3,4))
ones_arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
# 3D one's array

ones_arr = np.ones(((2,3,5)))
ones_arr

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [9]:
# creating numpy array with specific value by using full method

# 1D ARRAY FILLED WITH 90
arr = np.full(5,90)
arr

array([90, 90, 90, 90, 90])

In [10]:
# 2D ARRAY FILLED WITH 10
arr = np.full((3,5),10)
arr

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [11]:
# 3D ARRAY FILLED WITH 9
arr = np.full(((3,2,5)),9)
arr

array([[[9, 9, 9, 9, 9],
        [9, 9, 9, 9, 9]],

       [[9, 9, 9, 9, 9],
        [9, 9, 9, 9, 9]],

       [[9, 9, 9, 9, 9],
        [9, 9, 9, 9, 9]]])

In [12]:
# Identity matrix : Having diagonal values with ones.

identity = np.eye(4)
identity

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### random() : It is used to generate random elements

In [14]:
# 1D ARRAY OF RANDOM ELEMENTS
# RAND() : GENERATES RANDOM ELEMENTS BETWEEN O AND 1
# RAND() FUNCTION USING UNIFORM DISTRIBUTION WHILE SELECTING THE VALUES

np.random.rand(5)

array([0.09594346, 0.35225477, 0.82916544, 0.76556523, 0.17090016])

In [17]:
# 2D array of random elements (0 to 1) using rand()
np.random.rand(2,3)

array([[0.09057567, 0.18588369, 0.47135321],
       [0.77940848, 0.47979464, 0.03043288]])

In [18]:
# 3D array of random elements (0 to 1) using rand()
np.random.rand(2,2,4)

array([[[0.17524384, 0.80791351, 0.25779293, 0.17908805],
        [0.04640905, 0.63135186, 0.27591582, 0.73055659]],

       [[0.65635406, 0.92992474, 0.71344896, 0.22678619],
        [0.70366222, 0.60066199, 0.62508186, 0.07980487]]])

In [19]:
# random() : random works same as rand() function
# random() function receives the input in tuple format
np.random.random(10)

array([0.88696728, 0.62450573, 0.8246274 , 0.62919078, 0.5669664 ,
       0.61346004, 0.34889414, 0.03992672, 0.72152152, 0.45181362])

In [20]:
np.random.random((2,3))

array([[0.12912108, 0.58292298, 0.90574029],
       [0.80866778, 0.96438583, 0.91310049]])

In [21]:
# randn() : Generates most of values in between -3 to +3
# Here n stands for standard normal distribution (mean = 0, sd = 1)

#1D
np.random.randn(15)

array([ 0.10292361, -1.03597906,  0.14075937,  0.43202472,  1.60330842,
        0.0142343 , -0.5507004 ,  0.48309761, -0.2492982 ,  0.30284046,
       -0.75652626, -0.17664892,  1.64929409,  0.19252499, -0.48542478])

In [22]:
# 2D
np.random.randn(2,3)

array([[ 0.64840055, -0.32842458,  0.28429864],
       [ 0.8401732 , -0.63732378, -1.02205839]])

In [24]:
# randint() : It generates random integer elements between a range
rand_int = np.random.randint(1,10,15) 
# (a,b,c) : a is start and inclusive, b is end and exclusive and c is count
rand_int

array([7, 5, 6, 6, 8, 6, 2, 4, 8, 7, 9, 5, 8, 3, 5])

In [25]:
# 2D 
rand_int = np.random.randint(1,10,(2,6))
rand_int

array([[1, 5, 6, 9, 3, 2],
       [5, 9, 3, 8, 4, 4]])

In [28]:
# choice() : It works specifically on catagorical data.
# choice() function is used for selecting random elements from categorical list

arr = np.array(['raj','vishnu','venkat','krishna'])
np.random.choice(arr,size = 2)

array(['raj', 'venkat'], dtype='<U7')

In [27]:
# It wont give the same names repeatedly
np.random.choice(arr,size = 2,replace = False)

array(['raj', 'vishnu'], dtype='<U7')

In [29]:
np.random.choice(arr,size = 10)

array(['raj', 'vishnu', 'venkat', 'krishna', 'venkat', 'venkat', 'venkat',
       'raj', 'vishnu', 'venkat'], dtype='<U7')

In [32]:
# giving the probability of getting every name
np.random.choice(arr,size = 10,p=[0.1,0.2,0.5,0.2])

array(['raj', 'venkat', 'venkat', 'venkat', 'raj', 'vishnu', 'venkat',
       'raj', 'venkat', 'raj'], dtype='<U7')

In [33]:
# arange() : creates a sequence of elements
arr = np.arange(1,10,2) # arange(start,end,step)
arr

array([1, 3, 5, 7, 9])

In [40]:
# shuffle() : re-arranges the elements
# shuffle() function rearrange the elements in the same array.
np.random.shuffle(arr)
arr

array([5, 9, 3, 1, 7])

In [39]:
# permutation() function returns new shuffled array
arr2 = np.random.permutation(arr)
arr2

array([3, 9, 5, 7, 1])

In [44]:
#linspace() : linearly spaced numpy array
arr3 = np.linspace(1,10,5)
arr3

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])